# Generated by Django 5.2.8 on 2025-12-10 13:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campañas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaña',
            old_name='regla',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='campaña',
            name='canal',
        ),
        migrations.RemoveField(
            model_name='campaña',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='campaña',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='campaña',
            name='creador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='campañas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaña',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaña',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('fallida', 'Fallida')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='campaña',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaña',
            name='objetivo_etiquetas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='campaña',
            name='programada_para',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaña',
            name='tipo',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('notificacion', 'Notificación Interna')], default='email', max_length=20),
        ),
    ]
