# Generated by Django 5.2.8 on 2025-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cotizacion_descuento_cotizacion_impuestos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
