# Generated by Django 5.2.8 on 2025-12-07 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id_pyme', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('giro', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=200)),
                ('región', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_interno', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pymes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
