# Generated by Django 5.2.8 on 2025-12-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyme',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
