# Generated by Django 5.2.8 on 2025-12-10 12:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campañas', '0001_initial'),
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fecha_envio',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='estado',
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destino_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('error', 'Error')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='leida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='campaña',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='campañas.campaña'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('sistema', 'Sistema'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('stock_bajo', 'Stock Bajo'), ('venta', 'Venta'), ('cotizacion', 'Cotización'), ('campaña', 'Campaña')], default='sistema', max_length=30),
        ),
    ]
