# Generated by Django 5.2.8 on 2025-11-20 12:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyme',
            fields=[
                ('id_pyme', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_interno', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('retencion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='pyme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='productos.pyme'),
            preserve_default=False,
        ),
    ]
