# Generated by Django 5.2.8 on 2025-12-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pyme',
        ),
        migrations.DeleteModel(
            name='Pyme',
        ),
    ]
