# Generated by Django 5.2.8 on 2025-12-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
        ('productos', '0005_etiqueta_producto_etiquetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='productos.etiqueta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
